steps:
    - id: build-n-push
      name: "gcr.io/kaniko-project/executor:latest"
      args:
          - --destination=gcr.io/$PROJECT_ID/${_INSTANCE_NAME}:latest
          - --cache=true
          - --build-arg=NODE_ENV=${_NODE_ENV}

    - id: deploy-gcrun
      name: "gcr.io/google.com/cloudsdktool/cloud-sdk:alpine"
      entrypoint: gcloud
      args:
          [
              "run",
              "deploy",
              "${_INSTANCE_NAME}",
              "--image",
              "gcr.io/$PROJECT_ID/${_INSTANCE_NAME}:latest",
              "--region",
              "${_REGION}",
          ]

timeout: 1200s

substitutions:
    _INSTANCE_NAME: xxx
    _NODE_ENV: xxx
    _REGION: asia-southeast1
